layer_dependencies:
  ods: []
  dwd:
    - "ods"
  dim:
    - "dwd"
  dwm:
    - "dim"
  dws:
    - "dwm"
  ads:
    - "dws"

sources:
  ods_fund_etf_spot:
    path: "lake/raw/daily/fund_etf_spot"
    format: "csv"
  ods_etf_universe_whitelist:
    path: "lake/raw/daily/etf_universe_whitelist/local"
    format: "csv"
  ods_fund_etf_history:
    path: "lake/raw/daily/fund_etf_history"
    format: "csv"
  ods_trade_date_hist:
    path: "lake/raw/daily/trade_date_hist"
    format: "csv"

# table_dependencies:
#   dwd:
#     dwd_daily_stock_price: []
