layer_dependencies:
  ods: []
  dwd:
    - "ods"
  dim:
    - "dwd"
  dwm:
    - "dim"
  dws:
    - "dwm"
  ads:
    - "dws"

sources:
  ods_fund_names_em_akshare:
    path: "lake/raw/daily/fund_name/akshare/em"
    format: "csv"
  ods_tool_trade_date_hist_sina_akshare:
    path: "lake/raw/daily/tool_trade_date_hist/sina/akshare"
    format: "csv"
  ods_fund_etf_spot_em_akshare:
    path: "lake/raw/daily/fund_etf_spot/akshare/em"
    format: "csv"

# table_dependencies:
#   dwd:
#     dwd_daily_stock_price: []
