extractors:
  - target: fund_price_akshare
    tags: ["extractor", "akshare", "fund"]
    destination_key_template: "lake/raw/daily/fund_price/akshare/dt={PARTITION_DATE}/data.csv"
    fetcher: "dags.extractor.fetch_fund_price_akshare:fetch_fund_price_akshare"

  - target: stock_price_akshare
    tags: ["extractor", "akshare", "stock"]
    destination_key_template: "lake/raw/daily/stock_price/akshare/dt={PARTITION_DATE}/data.csv"
    fetcher: "dags.extractor.fetch_stock_price_akshare:fetch_stock_price_akshare"

  # - target: fund_price_tushare
  #   tags: ["extractor", "tushare", "fund"]
  #   destination_key_template: "lake/raw/daily/fund_price/tushare/dt={PARTITION_DATE}/data.csv"
  #   fetcher: "dags.extractor.fetch_fund_price_tushare:fetch_fund_price_tushare"

  - target: stock_price_tushare
    tags: ["extractor", "tushare", "stock"]
    destination_key_template: "lake/raw/daily/stock_price/tushare/dt={PARTITION_DATE}/data.csv"
    fetcher: "dags.extractor.fetch_stock_price_tushare:fetch_stock_price_tushare"
